
import 'package:get/get.dart';


class GlobalVariable {
  static RxInt selectedIndex = 0.obs;
  static RxInt notificationCount = 0.obs;
  static RxBool isDarkTheme = false.obs;
  static String token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWZmN2E2ZTIwNGM4NTRlZWExNTRlZjE4Yjk4NmNhNTk4NjRhNzQ1ZWM1MTZjMzY5MjdkOWYwZmI1MzZlZDdmMjNlM2MzMzcxZjg3NzEwNTIiLCJpYXQiOjE2NzE3MDY1MjAuNzY5Mjg0LCJuYmYiOjE2NzE3MDY1MjAuNzY5Mjg5LCJleHAiOjE3MDMyNDI1MjAuNzE3MDEyLCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.LfIiRKgAV4J7qOv3bFkki_Rwf8bDWi2Ul8GPXLIBmub0NWnfN8LIXjhNR_WxFUK7Wy1vp0PlfpdjreQz0NUkACgp8VUezcwn3a3-HMbJEs3K1DEUWDuF0jJeMaStasAclT6LLeE9vQOg4C6VVNbOaK2TvISacqh3JHa6RR3ns4kLQxJl1Tz0L489CrsMoyab6ZcGJSP8K70LKaqtWJBHVxQAiTzHFa4WBvrp85Yzp8fStEsgIsHYqSjo5g4t7Rr_PPXtZD74zrsNNNcVwFDP2Yrc8ypmtsavixpDXQebt2XrBscZVpW6jWRbDpnIxjJ030bEt3P704lnEjGHGHOhIIy-TQm2FUr6OT9qehjE_3TyYUtDb5ZiTgS_xgrEKGL71xQ8WFuWvQEapgwdKdKG1pW-2oQk6j_Mjev01z1_naSzKIibmxgCLnpjyscSB7xbOskvtIb79wXilmMxLzxNaycXY6wR-3_QV9MxjoJrdF-xcDYMKI7r7JaK2cPAsmTIgS2O3fJJMfSX-urm6x5DLVUcnadPjlfreAYOsjzK4nCJLCxVkj3KfUvcrDK5et7PsN1ocrASt0OHgzrXyLiiojYVZQDv9VORigJER_mftTDoqj8WuMn7DMawBuCcN_rj6gB4aOs9BnRTjDmERQ-T3nx6SV8JZbkLIUkzrMoZ--w';
  static RxBool showLoader = false.obs;
  static RxBool showNoInternet = false.obs;
 // static UserModel user = UserModel();
  static int? checkValue = 1;
}
